### ISSUE TITLE
Bug: StreamMusic with navidrome over HTTPS/TLS 无法获取封面

### ISSUE THREAD

**Issue by Arcaneing** [gitbobobo/StreamMusic#692]
### Steps to reproduce(重现步骤)

1. 使用docker-compse 启动navidrome
```yaml
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "14533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "/uuid"
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
    volumes:
      - "./data:/data"
      - "/mov/music:/music:ro"
```
2. 使用nginx代理http
```nginx
server {
  listen 10099 ssl;
  server_name domain;

  # SSL配置
  ssl_certificate /etc/certbot/domain/cert1.pem;
  ssl_certificate_key /etc/certbot/domain/privkey1.pem;
  ssl_trusted_certificate /etc/certbot/domain/chain1.pem;
  ssl_protocols TLSv1.2 TLSv1.3;

  # 设置最大上传文件大小
  client_max_body_size 32M;

  location /uuid {
    proxy_pass http://localhost:14533/uuid;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
  location / {
      deny all;
  }
}
```

3. 使用StreamMusic建立连接
4. 刷新专辑列表，无法展示封面。

### Expected results(预期结果)

封面位于:
 https://domain:port/uuid 正常显示
 http://ip:port/uuid 正常显示

### Actual results(实际结果)

封面位于:
 https://domain:port/uuid 无法获取
 http://ip:port/uuid 正常显示

封面不会主动获取
(通过抓包显示未主动请求image)

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

0.53.3

### Client Version(客户端版本)

V1.3.3

### Operating System(操作系统)

iOS

### Connection Type(连接类型)

Direct Mode(直连模式), Library Mode(媒体库模式)

### Additional Information(附加信息)

![1731906935450](https://github.com/user-attachments/assets/3a3eab00-2153-4c7f-bf8f-c46e407db63f)
抓包显示在https环境下，app不会主动请求封面。
无法获取更多日志信息
